### ISSUE TITLE
exception 

### ISSUE THREAD

**Issue by enoola** [ninsuo/leboncoin-alert#2]
php version : 7.1.12, 7.1.18

config file : 
urls:
    search lbc velo: 'http://www.leboncoin.fr/recherche/?text=velo&regions=12&owner_type=private'
    search lbc velo course: 'https://www.leboncoin.fr/recherche/text=velo%20course&regions=12&owner_type=private'

php run.php

PHP Fatal error:  Uncaught InvalidArgumentException: The current node list is empty. in /home/ninsuo/enolatmp/leboncoin-alert/vendor/symfony/dom-crawler/Crawler.php:565
Stack trace:
#0 /home/ninsuo/enolatmp/leboncoin-alert/vendor/ninsuo/leboncoin-crawler/src/Fuz/LeBonCoin/Crawler.php(59): Symfony\Component\DomCrawler\Crawler->text()
#1 /home/ninsuo/enolatmp/leboncoin-alert/run.php(8): Fuz\LeBonCoin\Crawler->getAds('http://www.lebo...', 100)
#2 {main}
  thrown in /home/ninsuo/enolatmp/leboncoin-alert/vendor/symfony/dom-crawler/Crawler.php on line 565

**Comment by ninsuo** [comment]
they probably changed their payload, having a look 👍 
thanks for the notice

**Comment by ninsuo** [comment]
they seem to block non-web browsers (eg. using a solution like datadome.co) 

```
string(236) "You have been blocked#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}Please enable JS and disable any ad blockervar dd={'cid':'AHrlqAAWL6VZw==','hsh':'05B3099D973'}"
```

will be too tough to bypass
